safe: false
title: born2code.net
description: Yet Another Programming Blog
url: http://born2code.net
markdown: redcarpet
rdiscount:
  extensions: [smart]
permalink: /blog/:year/:month/:day/:title
pygments: true
exclude: ["_config.json", "README.md", "scss", "post-deploy-tests.sh", "Rakefile", "Gemfile", "Gemfile.lock", "wercker.json"]
paginate: 3
content_assets_base: /assets/posts/
