safe: false
name: born2code.net
description: Yet Another Programming Blog
url: http://born2code.net
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /blog/:year/:month/:day/:title
pygments: true
exclude: ["config.json", "README.md", "scss", "Termfile"]
paginate: 5
