safe: false
name: born2code.net
description: Yet Another Programming Blog
url: http://born2code.net
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /blog/:year/:month/:day/:title
pygments: true
exclude: ["_config.json", "README.md", "scss", "wercker.json"]
paginate: 10
assetbase: http://born2code.net/assets/posts
assets:
  baseurl: http://born2code.net/assets/posts
