name: born2code.net
description: Yet Another Programming Blog
url: http://born2code.net
markdown: redcarpet2
lsi: true
source: source
permalink: /blog/:year/:month/:day/:title
pygments: true
exclude: ["mkfile"]
redcarpet:
  extensions: ["fenced_code_blocks"]
